services:
  registry-mirror:
    image: ${REGISTRY_HOST}/registry-mirror
    build:
      context: ../src
      additional_contexts:
        docker: ../docker
      dockerfile: ../docker/ruby/Dockerfile
    ports:
      - "7000:7000"
